// Every artist already credited somewhere in the song library, ordered by how
// often they appear — so the most-used names surface first when the field is
// opened with nothing typed.
//
// One spelling per artist: the variants that had crept in — misspellings, bare
// first names, "&" vs "and" — were merged into the canonical name, which kept
// the best rank any of its variants held. Adding a second spelling of a name
// that is already here undoes the point of the list.
//
// It only *suggests*, though; the artist field still accepts free text, because
// no fixed list can cover every local worship leader. The list lives in its own
// module (rather than in constants.ts) so it can be code-split: nothing loads
// these strings until someone actually opens the artist field.
export const songArtists: string[] = [
  "Hillsong Worship",
  "Nigerian worship",
  "Bethel Music",
  "Hillsong UNITED",
  "Elevation Worship",
  "Chris Tomlin",
  "sac",
  "Don Moen",
  "Michael W. Smith",
  "Ron Kenoly",
  "Phil Wickham",
  "Kirk Franklin",
  "Nathaniel Bassey",
  "Tasha Cobbs Leonard",
  "Nicole C. Mullen",
  "Donnie McClurkin",
  "God's Blaze Altar",
  "Dunsin Oyekan",
  "Celestial Hymn",
  "William McDowell",
  "HOP",
  "Israel Houghton",
  "Mercy Chinwo",
  "Travis Greene",
  "Loveworld Singers",
  "Vashawn Mitchell",
  "Matt Redman",
  "Todd Dulaney",
  "Hezekiah Walker",
  "Israel & New Breed",
  "Sinach",
  "Moses Bliss",
  "Passion",
  "Maverick City Music",
  "Maranatha! praise band",
  "Cody Carnes",
  "Eben",
  "Frank Edwards",
  "Ada Ehi",
  "Cory Asbury",
  "Judikay",
  "CeCe Winans",
  "Salvation Voices",
  "Lara George",
  "Phil Thompson",
  "Planetshakers",
  "Sola Allyson",
  "Sonnie Badu",
  "Victoria Orenze",
  "Tim Godfrey",
  "Panam Percy Paul",
  "Tope Alabi",
  "Darlene Zschech",
  "Jonathan McReynolds",
  "Limoblaze",
  "JayMikee",
  "Kari Jobe",
  "TY Bello",
  "Donald Lawrence & The Tri-City Singers",
  "Mike Abdul",
  "Nosa",
  "Minister GUC",
  "Kaestrings",
  "Joe Mettle",
  "Newsboys",
  "Peterson Okopi",
  "Chioma Jesus",
  "Maranatha! Music",
  "Chief Commander Ebenezer Obey",
  "Matthew West",
  "Midnight Crew",
  "The Maranatha Singers",
  "CityAlight",
  "Hillsong",
  "Anendlessocean",
  "Covenant Worship",
  "Psalm",
  "Lakewood Music",
  "LVCU",
  "Brandon Lake",
  "Fred Hammond",
  "Lucia Parker",
  "Pat Barrett",
  "Hillsong Kids",
  "Pat Uwaje-King",
  "UPPERROOM",
  "Amy Grant",
  "Femi Okunuga",
  "Musikatha",
  "Free Chapel Music",
  "Pastor Emmanuel Iren",
  "Yolanda Adams",
  "Chris Delvan Gwamna",
  "Marty Nystrom",
  "Miel San Marcos",
  "Randy Rothwell",
  "COP",
  "David Dam",
  "Neon Adejo",
  "Sunmisola Agbebi",
  "Todd Galberth",
  "Gbenga Akinfenwa",
  "The Belonging Co",
  "David G",
  "Elevation Worship & Maverick City Music",
  "God’s Property",
  "Greatman Takit",
  "Jesus Image",
  "Nigerian Praise & Worship",
  "Prospa Ochimana",
  "rrcc choir",
  "Samsong",
  "Steve Crown",
  "BJ Putnam",
  "Folabi Nuel",
  "Maverick City Music & Kirk Franklin",
  "Min. Fortune",
  "Sis. Chinyere Udoma",
  "The Worship Initiative",
  "David & Nicole Binion",
  "E-Daniels",
  "Ebuka Songs",
  "Gaise Baba",
  "Joe Praize",
  "Lawrence Oyor",
  "Monique",
  "Mosaic MSC",
  "Paul Tomisin",
  "Steffany Gretzinger",
  "Tauren Wells",
  "EGN Worship",
  "ELI-J",
  "Florocka",
  "Freke Umoh",
  "Jesus Culture",
  "Josiah Queen",
  "Marvin Sapp",
  "Matt Maher",
  "Mr M & Revelation",
  "Ordinarium",
  "Preye Odede",
  "Solomon Lange",
  "VOUS Worship",
  "Alvin Slaughter",
  "Anne Wilson",
  "Evang. (Dr). Bola Are",
  "Lionel Peterson",
  "Mali Music",
  "Tiffany Hudson",
  "William Murphy",
  "Dr Paul Enenche",
  "Esther Oji",
  "GGPIC",
  "Pastor Christosin Olalere",
  "Tori Kelly",
  "We The Kingdom",
  "dare david",
  "EGN",
  "Gateway Worship",
  "Jahdiel",
  "Kenny Kore",
  "Osinachi Nwachukwu",
  "Praise Africa",
  "Dr Sarah K",
  "Shout Praises Kids",
  "Theophilus Sunday",
  "Uche Agu",
  "Victor Thompson",
  "Women of Faith",
  "Abbey Ojomu",
  "BOAZ DANKEN",
  "Bob Fitts",
  "BUKOLA BEKES",
  "Christine D’Clario",
  "Kairos City Fellowship",
  "Keith & Kristyn Getty",
  "Oniwaya Choir",
  "Rommel Guevara",
  "Sinmidele",
  "Spring Worship",
  "Terry MacAlmon",
  "Benjamin Dube",
  "Brooke Ligertwood",
  "Darwin Hobbs",
  "Dr Becky Paul-Enenche",
  "Elevation Collective",
  "Gateway Worship Español",
  "GCA",
  "Geoffrey Golden",
  "Grace Lokwa",
  "greater grace",
  "gugun",
  "Housefires",
  "Jonathan Nelson",
  "Jubilee Worship",
  "Kutless",
  "Luis Baldomaro",
  "LVCU - Psalm",
  "LW Singers",
  "manosh",
  "MJ Flores",
  "Sammie Okposo",
  "Symphony Worship",
  "The Recording Collective",
  "The Walls Group",
  "Victory Band",
  "Victory Worship",
  "Abishek",
  "Adrienne Bailon",
  "Benita Okojie",
  "Big Daddy Weave",
  "Blesson Memana",
  "Bright Ones",
  "Chandler Moore",
  "charis choir",
  "Charles Jenkins",
  "Dena Mwana",
  "Drass",
  "Eddie James",
  "Gabriel Eziashi",
  "GMS Live",
  "Hope Filipino Worship",
  "Iglesia Luz & Sal",
  "J.J. Hairston & Youthful Praise",
  "Jesus One Generation",
  "Josh Baldwin",
  "Josh Groban",
  "JPCC Worship",
  "Kari Jobe & Cody Carnes",
  "Kent Henry",
  "Kestin Mbogo",
  "Kurt Carr",
  "Lecrae",
  "Mack Brock",
  "MercyMe",
  "Micah Stampley",
  "Naomi Raine",
  "NBCFC Worship",
  "Odunayo Adebayo",
  "Paul Wilbur",
  "Prinx Emmanuel",
  "Radiance",
  "Sandi Patty",
  "Steven Curtis Chapman",
  "The Brooklyn Tabernacle Choir",
  "Third Day",
  "TobyMac",
  "Tye Tribbett",
  "VICTORIOUS VOICES",
  "WorshipMob",
  "Anonymous",
  "Bam Crawford’s Purpose",
  "CAC HYMN",
  "Casting Crowns",
  "Cedarmont Kids",
  "Celestial Hymn (English)",
  "Charity Gayle",
  "CHRIS",
  "CIS",
  "Clint Brown",
  "Crowder",
  "CTUE Adoracion",
  "Dr. Ipyana",
  "EGN Media",
  "Essence of Worship",
  "EUNICE NJERI",
  "Evang. Ojo Ade",
  "Femi Onilado",
  "Fiya",
  "Florence Mureithi",
  "Gaither Family",
  "Gateway Worship Português",
  "George Ratcliffe Woodward",
  "Graham Kendrick",
  "Heritage Singers",
  "Hlengiwe Mhlaba",
  "Jaci Velasquez",
  "jajo",
  "Jeremy Riddle",
  "JJ Hairston",
  "JNIC",
  "John Lisu",
  "jovert madera",
  "Keith Staten",
  "Lauren Daigle",
  "Mairo Ese",
  "Malayang Pilipino Music",
  "Martha Munizzi",
  "Martin Smith",
  "Minstrel T-Philz",
  "MOG",
  "nath",
  "North Point Worship",
  "Oasis Ministry",
  "Obinna",
  "Outburst",
  "paul clement",
  "Pelumi Deborah",
  "PJ Morton",
  "Pst. Twina H",
  "Rotimikeys",
  "SAINTS COMMUNITY",
  "Sakari Heikkilä",
  "Salvation Choir",
  "SDAH",
  "Seventh Day Slumber",
  "Skuare",
  "Sonia/ Kairos City Fellowship",
  "Sounds of Worship",
  "Spirit of Prophecy",
  "Steve Kuban",
  "Stichting Opwekking",
  "Tamela Mann",
  "Tim Hughes",
  "Tom Inglis",
  "Truth (CCM)",
  "Twice Música",
  "Vertical Worship",
  "Victorious Choir",
  "Worship Central",
  "yoruba praise",
  "Adeyinka Alaseyori",
  "Andy Denton",
  "Anna Golden",
  "Audrey Assad",
  "Benjamin William Hastings",
  "Billy Sprague",
  "Brandon Heath",
  "Bruna Karla",
  "Bryan & Katie Torwalt",
  "Chris Tomlin & Elevation Worship",
  "Common",
  "Crystal Lewis",
  "Danilo Montero",
  "Deitrick Haddon",
  "Diana Hamilton",
  "Gabriela Rocha",
  "Gungor",
  "Hillsong London",
  "Hillsong Worship & Tasha Cobbs Leonard",
  "IDMC Gospel Soul Choir",
  "James Fortune & Fiya",
  "Jeremy Camp",
  "Joshua Banjo",
  "Judy Jacobs",
  "Karen Clark Sheard",
  "Kathy Troccoli",
  "Kay Wonder (ft Okey Sokay)",
  "Kierra Sheard",
  "Kristene DiMarco",
  "LaRue Howard",
  "Liberty Worship Collective",
  "Life.Church Worship",
  "Mariah Carey, Khalid, & Kirk Franklin",
  "Michael Gungor",
  "Misty Edwards",
  "Moses Bliss & Mercy Chinwo",
  "Neon Feather",
  "Niyi Fadipe",
  "P.Daniel Olawande",
  "Paul Baloche",
  "Prince Gozie Okeke",
  "Q Parker",
  "Rend Collective",
  "Seth & Nirva",
  "Sheila E.",
  "Stevie Wonder",
  "Sugar Creek Worship",
  "Sunday Service Choir",
  "Thomas Rhett",
  "Tommy Iceland",
  "Wale Adenuga",
  "Wayne Jones & Amy Hayashi-Jones",
  "We Are Messengers",
  "Whitney Houston",
  "10,000 Fathers",
  "Aaron Shust",
  "Acquire The Fire",
  "Alden Richards",
  "Aline Barros",
  "Amber Bullock",
  "Andrew Pulido",
  "Anne Wilson & Chris Tomlin",
  "Ant Clemons & Justin Timberlake",
  "Anthem Lights",
  "Antioch Music",
  "Ashmont Hill",
  "Aslandia",
  "Ayesha Erotica",
  "Banky W.",
  "BeBe Winans",
  "Ben Tankard",
  "Ben Wylen",
  "Benjamin William Hastings & Worship Together",
  "Bethany Dillon",
  "Bethel Music & kalley",
  "Bethel Music & Kristene DiMarco",
  "Bingo Boys",
  "Blackstreet",
  "Blessing Offor",
  "Brenton Brown",
  "Brett Young",
  "Bri Babineaux",
  "Brian & Jenn Johnson",
  "Bryan & Katie Torwalt & Cody Carnes",
  "Bryson Price",
  "Building 429",
  "CAIN & Essential Worship",
  "Caleb and Kelsey",
  "Cam Noble",
  "Capital Kings",
  "Carman",
  "Carrie Underwood",
  "Casting Crowns & Phil Wickham",
  "CCM Artists & Friends",
  "Chance the Rapper",
  "Chandler Moore, Phil Wickham & Maverick City Music",
  "Charles Billingsley",
  "Chimzy Wali",
  "Chris Davenport",
  "Chris Morgan",
  "Chris Rodriguez",
  "Chris Tomlin & Blessing Offor",
  "Chris Tomlin & Brandon Lake",
  "Chris Tomlin & Steffany Gretzinger",
  "Chris Tomlin & Tyler Hubbard",
  "Christon Gray",
  "CoconetTV",
  "Cody Carnes & Brandon Lake",
  "Cody Carnes & David Leonard",
  "Cody Carnes & Leeland",
  "Cody Carnes & Natalie Grant",
  "Coffey Anderson",
  "Continental",
  "Coro Adolescentes D5",
  "Cross Point Church",
  "Da’ T.R.U.T.H.",
  "Da’ T.R.U.T.H. & Limoblaze",
  "Damarea Ogbuewu",
  "Danny Gokey",
  "Darey",
  "Darrell Evans",
  "Dave Pettigrew",
  "Deborah Cox",
  "Destiny’s Child",
  "DOE",
  "Dulaneyland Music",
  "Edreez khalifa",
  "Ella Mai",
  "Erigga",
  "Erik Santos",
  "Ernie Haase & Signature Sound",
  "Essential Worship",
  "Evan Craft",
  "Evang. Dare Melody",
  "Evans Ogboi",
  "Flo",
  "for KING & COUNTRY",
  "for KING & COUNTRY, Tori Kelly & Kirk Franklin",
  "Forward City & Travis Greene",
  "Gabby Barrett",
  "Gatton & sxxnt.",
  "GAWVI",
  "Gbolahan Odukoya",
  "GemStones",
  "Genevieve Linkowski",
  "GK Lovsång",
  "Gloria Ekwuobi (Kido)",
  "Glowreeyah /( Ft Nathaniel Bassey)",
  "Godfrey Gad",
  "Greg Long",
  "Guvna B",
  "Gymani",
  "Have Mercy",
  "Heavenly Voices",
  "Hélio Borges",
  "Hillsong Instrumentals",
  "Hillsong Young & Free",
  "Hollyn",
  "Holy Communion Instrumental Duo",
  "Honor & Glory",
  "I AM THEY",
  "Influence Music",
  "Intimidad Music",
  "Iris Gonzales",
  "Isaac Carree",
  "J. Moss",
  "Jacob Collier",
  "Jason Malachi",
  "JDI-Jay",
  "Jermaine Dupri",
  "Jesse Morgan",
  "Jesus Image, Steffany Gretzinger & Jeremy Riddle",
  "Jimi Cravity",
  "John Tesh",
  "Jotta A",
  "Juanita du Plessis",
  "Julia Vitória",
  "Justin Timberlake",
  "JustPierre",
  "Kanye West",
  "Kate White",
  "Kenny Rogers",
  "Kenoly Brothers",
  "Kim Burrell",
  "Kofi Karikari",
  "Kolawole Bekes ft Dunsin Oyekan",
  "Laura Story",
  "LIFE Worship",
  "LifeWay Worship",
  "Lincoln Brewster",
  "Living Word Worship",
  "Logan Holland",
  "Luke James",
  "Mandisa",
  "Marco Barrientos",
  "Marshall Marshall",
  "Maverick City Music & UPPERROOM",
  "Maverick City Musica & Maverick City Music",
  "Melodie Joy",
  "Meredith Andrews",
  "METTE",
  "Michael W. Smith & Darlene Zschech",
  "Miel San Marcos & Essential Worship",
  "Mike Oldfield",
  "Mosun Olaitan",
  "Music City Unites for Haiti",
  "Naaz",
  "Natalie Grant & Tasha Cobbs Leonard",
  "New Wine Worship",
  "Newday",
  "Nicki Minaj",
  "Nikki Leonti",
  "Niyi Adedokun",
  "Noel Robinson",
  "Okay Sokay",
  "ONOS",
  "Outbreakband, Urban Life Worship & Juri Friesen",
  "P. Diddy and the Bad Boy Family",
  "Passion & Travis Greene",
  "Pat Barrett & Dante Bowe",
  "Patitas",
  "Paul Baloche & Don Moen",
  "Pennell",
  "Pentatonix",
  "Peter CottonTale",
  "Phil Wickham & Brandon Lake",
  "Phil Wickham & Chris Quilala",
  "Phil Wickham & Christine D’Clario",
  "Phillips, Craig & Dean",
  "Point Of Grace",
  "Prestonwood Worship",
  "Princess Njideka",
  "R. Kelly",
  "Randy Travis",
  "Raspo",
  "Rebecca St. James",
  "Renee Spearman & Hezekiah Walker",
  "Rev. Fr. Ejike Mbaka C.",
  "REVERE",
  "REVERE, Darlene Zschech & William McDowell",
  "REVERE, Leeland & Lee University Singers",
  "Rezurrection",
  "Rheva Henry",
  "Ricardo Sanchez",
  "Richard Tito",
  "Rick Pino & Abbie Gamboa",
  "Rodney Jerkins",
  "Ryan Ofei",
  "Sair Pérez",
  "Sango",
  "Sara Paulson",
  "Sarah Reeves",
  "Scott Wesley Brown",
  "Seacoast Music",
  "Sean Curran",
  "Sean Feucht",
  "Serayah",
  "Serayah, Ahjah Walls & Koryn Hawthorne",
  "Shana Wilson-Williams",
  "Shane & Shane",
  "Sheena Lee",
  "Sheila Walsh",
  "Sidney Mohede",
  "SMASH Cast",
  "Songs of Salem",
  "Sonicflood",
  "Soul Survivor",
  "Sounds of Salem",
  "SOZO Sleep",
  "Steve Green",
  "Stu Garrard",
  "Susan Ashton",
  "Tasha Page-Lockhart",
  "Tauren Wells & Elevation Worship",
  "Taylor Mosby",
  "The Imperials",
  "The Island Inspirational All-Stars",
  "The Maker & The Instrument",
  "The Martins",
  "The McClures",
  "The Passion Cast",
  "The Rance Allen Group",
  "The Suffers",
  "Todd Agnew",
  "Tommee Profitt & Fleurie",
  "Travis Cottrell",
  "Travis Cottrell & Worship Together",
  "Tribl & Maverick City Music",
  "Tricia",
  "Trio Nascimento",
  "Trip Lee & Kirk Franklin",
  "Tunde Onijoba",
  "tyler richardson",
  "VeggieTales",
  "Vertical Worship & Essential Worship",
  "Vince Gill",
  "Vineyard Anaheim",
  "We The Kingdom & Tasha Cobbs Leonard",
  "Wes King",
  "William Matthews",
  "Woodlands Worship",
]
