import type { Emitter, EventType } from "mitt"
import type { User } from "~/store/auth"

export interface SubscriptionActiveDetails {
  id: string
  plan: string
  status: "active" | "trialing" | "inactive" | "canceled"
  expiresAt: string | null
  lastPaidAt: string | null
  canceledAt: string | null
  paystackSubscriptionCode: string | null
  amount: number | null
  currency: "NGN" | "USD" | null
  interval: "monthly" | "yearly" | null
}

export interface SubscriptionBillingRecord {
  id: string
  plan: string
  status: "active" | "inactive" | "canceled"
  amount: number | null
  currency: "NGN" | "USD" | null
  lastPaidAt: string | null
  expiresAt: string | null
  canceledAt: string | null
  createdAt: string
}

export interface SubscriptionDetails {
  churchName: string
  subscriptionPlan: "free" | "teams"
  isFreeTrial: boolean
  activeSubscription: SubscriptionActiveDetails | null
  billingHistory: SubscriptionBillingRecord[]
}

export interface BillingTransaction {
  _id: string
  provider: "paystack" | "dodo"
  providerReference: string
  status: "successful" | "failed" | "pending" | "reversed"
  kind: "initial_payment" | "renewal" | "unknown"
  amount: string
  currency: string
  reversedAmount: string | null
  occurredAt: string
  statusChangedAt: string
  failureReason: string | null
}

export interface PresentationObject {
  page: number
  imageUrl: string
}

export interface SongSetlistItem {
  id: string
  songId: string
  song: Song
  verseIndex: number
}

export interface SongSetlistData {
  songs: SongSetlistItem[]
  activeSongIndex: number
}

export interface Slide {
  _id?: string
  id: string // ID generated by client side
  index: number // Index of slide in the schedule array
  name: string
  type: string
  layout: string
  userId: string
  churchId: string
  scheduleId: string // ID could be generated client side but must be replaced upon upload.
  contents: Array<string>
  backgroundType?: string
  background?: string
  backgroundVideoKey?: string | null
  backgroundImageKey?: string | null
  title?: string // For hymn and song titles, also for scripture labels (e.g Ephesians 3:1)
  songId?: string // only for hymns/songs, could be [hymn.number] or [song.id]
  hasChorus?: boolean // only for hymns, to tell if the hymns include a chorus
  hymnVerseIndex?: number // 0-based index of current hymn verse, used for chorus navigation
  hymnSubVerseIndex?: number // 0-based chunk index inside the current verse/chorus
  hymnSubVerseTotal?: number // total chunks in the current verse/chorus
  data?: Song | Scripture | Hymn | Countdown | TimeSlideData | ExtendedFileT | SongSetlistData // for song/bible/hymn/file/setlist, Object mapped to Slide only on client
  slideStyle?: SlideStyle
  saved?: boolean
  createdAt?: string
  updatedAt?: string
  presentationObjects?: PresentationObject[] // only for presentation slides
  presentationPageIndex?: number // 0-based index of the currently displayed page
  slideMode?: "slide" | "overlay"
  /** Per-asset upload history, safe to persist and share across devices. */
  mediaCloudSync?: Record<string, MediaCloudSyncRecord>
}

export interface Template {
  _id: string
  name: string
  description?: string
  slideId: string | Slide
  createdBy: string
  category: 'announcement' | 'worship' | 'sermon' | 'prayer' | 'general'
  thumbnail?: string
  createdAt: string
  updatedAt: string
}

// ── Schedule starter templates ──────────────────────────────────────────────
// A "schedule template" is a themed collection of slide *seeds* that get
// resolved into real slides (via useSlideCreation) when a new schedule is
// created from the template. This is separate from `Template` above, which is a
// single-slide "Slide Templates" feature.
export type ScheduleTemplateSeed =
  | { type: 'text'; heading?: string; subtitle?: string; body?: string }
  | { type: 'bible'; ref: string } // numeric "book:chapter:verse" label, e.g. "43:3:16-17"
  | { type: 'hymn'; number: string }
  | { type: 'song'; song: Song }
  | { type: 'song-setlist'; songs: Song[] }
  | { type: 'countdown'; time: string; label: string } // "HH:MM:SS", e.g. "00:05:00"
  | { type: 'media'; mediaType: 'image' | 'youtube'; url: string; name?: string }

export interface ScheduleTemplate {
  key: string
  label: string
  description: string
  image: string // preview thumbnail
  slides: ScheduleTemplateSeed[]
}

export interface Schedule {
  _id: string
  // id: string // ID generated by client side
  name: string
  authorId: string
  editorIds: Array<User> // sorted in the order of most recent person to edit a Slide, with most recent person being the 0th index
  churchId: string
  lastUpdated?: string
  createdAt?: string
  updatedAt?: string
}

export interface Alert {
  _id?: string
  id: string // ID generated by client side
  title: string
  icon: string
  style: string
  background: string
  speed?: number // Animation speed multiplier (0.5 = slow, 2 = fast)
  // position: string // top, bottom
}

export interface Countdown {
  _id?: string
  id: string // ID generated by client side
  time: string
  timeLeft: string
  content: string
  /** Remaining duration sent when playback starts so each output can tick locally. */
  remainingMs?: number
  // style: string
}

export interface TimeSlideData {
  id: string
  label: string
}

export interface QuickAction {
  icon: string
  name: string
  desc: string
  action: string
  actionArg?: string // Optional argument to pass when the action is emitted
  type?: string
  unreleased?: boolean
  featureFlag?: string // PostHog feature flag key to check
  bibleBookIndex?: string
  bibleChapterAndVerse?: string
  hymnIndex?: string
  songData?: Song
  countdownData?: Countdown
  searchableOnly?: boolean
  meta?: string
  tier?: 'free' | 'teams' // Subscription tier required for this action
  recentSearch?: boolean // Marks a recently opened item (e.g. recent Bible search), shows RecentClockIcon
}

export interface Scripture {
  label: string
  labelShortFormat: string
  version: string
  content: string | BibleVerse[]
}

export interface BibleVerse {
  book: string
  chapter: string
  verse: string
  scripture: string
}

export interface BibleVersion {
  id: string
  name: string
  isDownloaded: boolean
  copyrightContent: string
}

export interface Hymn {
  number: string
  title: string
  chorus: string
  verses: Array<string>
  author: string
  source: string
  meta: string
}

export interface Song {
  _id?: string
  id: string // ID generated by client side
  lyrics: string
  title: string
  artist: string
  album?: string
  cover?: string
  author?: string
  verses?: Array<string>
  isPublic?: boolean
  createdBy?: string
  churchId?: string
  createdAt?: string
  updatedAt?: string
  fromSaved?: boolean // client-side only, set when the song came from the personal library
}

export interface ExternalVideo {
  url: string
  type: string // "youtube" | "vimeo" | "other"
  name?: string
  thumbnail?: string
}

export interface Media {
  id: string
  content?: any
  remoteUrl?: string
  data?: ArrayBuffer | File | string | ExternalVideo
  createdAt?: string
  updatedAt?: string
}

export type LocalMediaBackend = "opfs" | "tauri-fs"
export type LocalMediaCategory =
  | "slide"
  | "presentation-page"
  | "background"
  | "preset"
export type LocalMediaKind = "image" | "audio" | "video"
export type MediaCloudSyncStatus =
  | "pending"
  | "uploaded"
  | "local-only"
  | "failed"
export type MediaCloudSyncReason =
  | "offline"
  | "quota"
  | "disabled"
  | "upload-error"

/** Cloud history is kept separately from the physical-file record. */
export interface MediaCloudSyncRecord {
  key: string
  groupId: string
  status: MediaCloudSyncStatus
  reason?: MediaCloudSyncReason
  remoteUrl?: string
  error?: string
  createdAt: string
  updatedAt: string
  uploadedAt?: string
}

/**
 * Searchable, device-local metadata for a binary file whose bytes live outside
 * IndexedDB. The `relativePath` is always relative to the platform's managed
 * media root and must never contain a user-supplied filename.
 */
export interface LocalMediaFileRecord {
  key: string
  groupId: string
  backend: LocalMediaBackend
  category: LocalMediaCategory
  kind: LocalMediaKind
  relativePath: string
  mimeType: string
  size: number
  originalName?: string
  remoteUrl?: string
  recoverable: boolean
  lastAccessedAt: string
  createdAt: string
  updatedAt: string
  storageVersion: 1
}

export interface BackgroundVideo {
  id: string
  url: string
}

export interface LibraryItem {
  id: string
  type: String
  content: Slide | Song
  createdAt?: string
  updatedAt?: string
}

export interface SlideStyle {
  blur?: number
  brightness?: number
  alignment?: string
  font?: string
  linesPerSlide?: number
  fontSize?: number // size in vw[viewportWidth]
  fontSizePercent?: number
  backgroundFillType?: string
  repeatMedia?: boolean
  isMediaPlaying?: boolean // also used to check if countdown is paused or is beginning
  mediaSeekPosition?: number // 0 or -1, -1 means not at the beginning
  isMediaMuted?: boolean
  windowPadding?: {
    left?: number
    right?: number
    top?: number
    bottom?: number
  }
  lettercase?: string
  lineSpacing?: string
  textOutlined?: boolean
  textBold?: boolean
  textLinesBackground?: boolean
  bibleVersion?: string
  theme?: string // Theme ID for slide styling (e.g., for Bible slides)
  overlayPlacement?: OverlayPosition
  overlayScale?: number
}

export type OverlayPosition =
  | "top-left"
  | "top-middle"
  | "top-right"
  | "middle"
  | "bottom-left"
  | "bottom-middle"
  | "bottom-right"

export interface OverlaySettings {
  position: OverlayPosition
  scale: number
}

export interface Advert {
  _id: string
  title: string
  url: string
  image: string
  createdAt: string
  updatedAt: string
}

export interface ExtendedFileT extends File {
  blob?: Blob
  url: string
}

export interface AppSettings {
  appVersion: string
  defaultBibleVersion: string
  defaultFont: string
  defaultBackground: {
    default?: {
      backgroundType: string
      background: string
      backgroundVideoKey: string | null
      backgroundImageKey?: string | null
    }
    hymn: {
      backgroundType: string
      background: string
      backgroundVideoKey: string | null
      backgroundImageKey?: string | null
    }
    bible: {
      backgroundType: string
      background: string
      backgroundVideoKey: string | null
      backgroundImageKey?: string | null
    }
    text: {
      backgroundType: string
      background: string
      backgroundVideoKey: string | null
      backgroundImageKey?: string | null
    }
  }
  slideStyles: SlideStyle
  overlaySettings?: OverlaySettings
  bibleVersions: Array<any> // Check app.vue for bible versions array in a list
  animations?: boolean // Transitions between slides (e.g. crossfade)
  microAnimations?: boolean // Micro/text animations within a slide (come-up etc.)
  verseTransitionStyle?: "off" | "fade" | "slide-up" // Verse/line-to-line transition within the same slide
  verseTransitionInterval?: number // Duration (seconds) of the verse/line-to-line transition
  footnotes?: boolean
  songAndHymnLabelsVisibility: boolean
  liveWindowFullscreen?: boolean // Whether live window opens in fullscreen mode
  closeLiveWindowWithOperator?: boolean // Whether live window closes when the operator tab/window closes
  ndiEnabled?: boolean // Device-local desktop NDI preference. Never synced to the backend.
  transcriptionAutoActions?: boolean
  transcriptionVoiceBibleVersionCommands?: boolean
  uploadVideosToCloud?: boolean // Upload video media slides to cloud (S3). Defaults to true.

  motionlessSlides?: boolean // deprecated
  transitionInterval?: number
  alertLimit?: number
  intermission?: {
    mode: "default" | "media" // "default" = church-branding screen (logo/name)
    backgroundType?: string // backgroundTypes.image | backgroundTypes.video
    background?: string // resolved URL (https / blob / object URL)
    backgroundVideoKey?: string | null // Device-local media key for video mode
    backgroundImageKey?: string | null // Device-local media key for image mode
  }
}

export interface OnlineUser {
  userId: string
  userName: string
  avatar: string
  scheduleId: string
  joinedAt: string
  theme: string
}

export interface AppState {
  activeAdvert: Advert | null
  schedules: Array<Schedule>
  activeSchedule: Schedule | null
  activeSlides: Array<Slide> // Returns all slides on CoW
  liveOutputSlidesId: Array<string> | null
  liveSlideId: string | null
  emitter: Emitter<Record<EventType, any>> | null
  settings: AppSettings
  backgroundVideos: Array<BackgroundVideo>
  alerts: Array<Alert>
  activeAlert: Alert | null
  activeOverlay: string
  activeOverlaySlide: Slide | null
  recentBibleSearches: Array<string>
  failedUploadRequests: Array<{ path: string; options: any; timestamp: number }>
  slidesLoading: boolean
  lastSynced: string
  bannerVisible: boolean
  bibleVersions: Array<any> // Check app.vue for bible versions array in a list
  activeSocket: WebSocket | null
  mainDisplayLabel: string
  mainDisplayScreen: Screen | null
  // Screen the stage display (confidence monitor) opens on. Empty when the
  // operator has not assigned one — the stage display then opens in a new tab.
  stageDisplayLabel: string
  stageDisplayScreen: Screen | null
  defaultMicrophoneId: string
  defaultCameraId: string
  // Realtime collaboration
  onlineUsers: Array<OnlineUser>
  slidesBeingEdited: Record<
    string,
    { userId: string; userName: string; avatar?: string; theme?: string }
  >
}
